import { CookiesProvider } from 'next-client-cookies/server';
import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "ANGINA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-neutral-100 text-black`}
      >
        <div id='page'>
          <CookiesProvider>
          {children}
          </CookiesProvider>
        </div>
      </body>
    </html>
  );
}
